security:
    ignored: /v2/api-docs
engine:
  timeout: 30
hdfs:
  superUser: ${hdfs.superuser:}
  clientKeytab: ${hdfs.keytab:}
  hiveUser: ${hdfs.hiveuser:}
  arcadiaUser: ${hdfs.arcadiauser:arcadia-user}
  vcapUser: ${hdfs.vcapuser:vcap}
yarn:
  cloudera:
    user: ${cloudera.user:}
    password: ${cloudera.password:}
    host: ${cloudera.address:}
    port: ${cloudera.port:}
group.mapping:
  url: ${hgm.url}
  kerberos:
    principal: ${hgm.principal:}
    principalKeyTab: ${hgm.principal.keytab:}
  https:
    username: ${hgm.username:}
    password: ${hgm.password:}
sentry.server:
  address: ${sentry.address:}
  port: ${sentry.port:8038}
  principal: ${sentry.principal:sentry}
impala.server:
  connectionUrl: ${impala.connectionUrl:}
  available: ${impala.available}
hive.server:
  connectionUrl: ${hive.connectionUrl}
  hdfsUri: ${hive.hdfsUri:hdfs://nameservice1/org/}
warehouse.client:
  clientKeyTab: ${warehouse.keytab:}
  superUser: ${warehouse.superuser:hive}
spring.oauth2.resource:
    id: cloud_controller
    jwt:
      keyUri: ${vcap.services.sso.credentials.tokenKey}
logging.level:
    org.apache.zookeeper: DEBUG
    org.trustedanalytics: DEBUG

logging.level.org.apache.zookeeper: DEBUG
