engine:
  timeout: 10
hdfs:
  superUser: ${hdfs.superuser:}
  clientKeytab: ${hdfs.keytab:}
  hiveUser: ${hdfs.hiveuser:}
group.mapping:
  url: ${hgm.url}
  kerberos:
    principal: ${hgm.principal:}
    principalKeyTab: ${hgm.principal.keytab:}
  https:
    username: ${hgm.username:}
    password: ${hgm.password:}
sentry.server:
  address: ${sentry.address:}
  port: ${sentry.port:8038}
  principal: ${sentry.principal:sentry}
sentry.client:
  clientKeyTab: ${sentry.keytab:}
  superUser: ${sentry.superuser:hive}

logging.level.org.apache.zookeeper: DEBUG
